# Home Assistant
- id: notify_if_an_update_is_available_for_home_assistant
  alias: Notify if an update is available for Home Assistant
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.family
    data:
      message: An update for Home Assistant is available.

# Laundry
- id: notify_if_washer_has_finished
  alias: Notify if washer has finished
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_washer_power_sensor
    to: 'off'
    for:
      minutes: 5
  action:
    service: notify.family
    data:
      message: The washer has finished its cycle.

# Living Room
- id: turn_on_xmas_lights_when_someone_arrives_home
  alias: Turn on X-mas lights when someone arrives home
  trigger:
    platform: state
    entity_id: group.family
    to: 'home'
  condition:
    condition: state
    entity_id: switch.living_room_sofa_corner_light_switch
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_sofa_corner_light_switch
    - service: notify.family
      data:
        message: The X-mas lights have been turned on.

- id: turn_on_xmas_lights_when_sun_sets_and_someone_is_home
  alias: Turn on X-mas lights when sun sets and someone is home
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: switch.living_room_sofa_corner_light_switch
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_sofa_corner_light_switch
    - service: notify.family
      data:
        message: The X-mas lights have been turned on.

- id: turn_off_xmas_lights_at_02_00
  alias: Turn off X-mas lights at 02:00
  trigger:
    platform: time
    at: '02:00:00'
  condition:
    condition: state
    entity_id: switch.living_room_sofa_corner_light_switch
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_sofa_corner_light_switch
    - service: notify.family
      data:
        message: The X-mas lights have been turned off.

# Hall
- id: notify_if_front_door_was_opened
  alias: Notify if front door was opened
  trigger:
    platform: state
    entity_id: binary_sensor.hall_front_door_sensor
    to: 'on'
  action:
    service: notify.family
    data:
      message: The front door was opened.

- id: turn_on_hall_light_when_door_is_opened_sun_is_set_and_nobody_is_home
  alias: Turn on hall light when door is opened, sun is set and nobody is home
  trigger:
    platform: state
    entity_id: binary_sensor.hall_front_door_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: switch.turn_on
    entity_id: switch.hall_presence_light_switch

- id: turn_on_hall_presence_light_when_sun_sets
  alias: Turn on hall presence light when sun sets
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.hall_presence_light_switch

- id: turn_off_hall_presence_light_when_sun_rises
  alias: Turn off hall presence light when sun rises
  trigger:
    platform: sun
    event: sunrise
    offset: -00:45:00
  action:
    service: switch.turn_off
    entity_id: switch.hall_presence_light_switch

# Garden
- id: turn_off_garden_lights_when_sun_rises
  alias: Turn off garden lights when sun rises
  trigger:
    platform: sun
    event: sunrise
    offset: -00:30:00
  action:
    - service: switch.turn_off
      entity_id: switch.basement_outdoor_lights_switch
    - delay: 00:00:10
    - service: notify.family
      data:
        data:
          photo:
            caption: The garden lights have been turned off.
            url: '{{ states.sensor.homeassistant_base_url.state ~ states.camera.rear.attributes.entity_picture }}'
        message: Message is ignored

- id: turn_on_garden_lights_when_sun_sets
  alias: Turn on garden lights when sun sets
  trigger:
    platform: sun
    event: sunset
    offset: +00:15:00
  action:
    - service: switch.turn_on
      entity_id: switch.basement_outdoor_lights_switch
    - delay: 00:00:10
    - service: notify.family
      data:
        data:
          photo:
            caption: The garden lights have been turned on.
            url: '{{ states.sensor.homeassistant_base_url.state ~ states.camera.rear.attributes.entity_picture }}'
        message: Message is ignored

# Garden: Sprinklers
- id: turn_off_garden_sprinklers_station_1_after_timer
  alias: Turn off garden sprinklers station 1 after timer
  trigger:
    platform: state
    entity_id: switch.garden_sprinklers_station_1_switch
    to: 'on'
  action:
    - delay: 00:{{ states.input_number.garden_sprinklers_station_1_slider.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.garden_sprinklers_station_1_switch

- id: turn_off_garden_sprinklers_station_2_after_timer
  alias: Turn off garden sprinklers station 2 after timer
  trigger:
    platform: state
    entity_id: switch.garden_sprinklers_station_2_switch
    to: 'on'
  action:
    - delay: 00:{{ states.input_number.garden_sprinklers_station_2_slider.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.garden_sprinklers_station_2_switch

- id: turn_off_garden_sprinklers_station_3_after_timer
  alias: Turn off garden sprinklers station 3 after timer
  trigger:
    platform: state
    entity_id: switch.garden_sprinklers_station_3_switch
    to: 'on'
  action:
    - delay: 00:{{ states.input_number.garden_sprinklers_station_3_slider.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.garden_sprinklers_station_3_switch

- id: turn_off_garden_sprinklers_station_4_after_timer
  alias: Turn off garden sprinklers station 4 after timer
  trigger:
    platform: state
    entity_id: switch.garden_sprinklers_station_4_switch
    to: 'on'
  action:
    - delay: 00:{{ states.input_number.garden_sprinklers_station_4_slider.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.garden_sprinklers_station_4_switch

- id: turn_off_garden_sprinklers_station_5_after_timer
  alias: Turn off garden sprinklers station 5 after timer
  trigger:
    platform: state
    entity_id: switch.garden_sprinklers_station_5_switch
    to: 'on'
  action:
    - delay: 00:{{ states.input_number.garden_sprinklers_station_5_slider.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.garden_sprinklers_station_5_switch

- id: turn_off_garden_sprinklers_station_7_after_timer
  alias: Turn off garden sprinklers station 7 after timer
  trigger:
    platform: state
    entity_id: switch.garden_sprinklers_station_7_switch
    to: 'on'
  action:
    - delay: 00:{{ states.input_number.garden_sprinklers_station_7_slider.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.garden_sprinklers_station_7_switch

# Garage
- id: mark_garage_door_just_opened
  alias: Mark garage door just opened
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_door_distance_sensor
    below: 30
  action:
    - service: input_select.select_option
      entity_id: input_select.select_option
      data:
        entity_id: input_select.garage_door_status_dropdown
        option: 'Just Opened'

- id: mark_garage_door_opened
  alias: Mark garage door opened
  trigger:
    platform: state
    entity_id: input_select.garage_door_status_dropdown
    to: 'Just Opened'
    for:
      minutes: 2
  action:
    - service: input_select.select_option
      entity_id: input_select.select_option
      data:
        entity_id: input_select.garage_door_status_dropdown
        option: Open

- id: mark_garage_door_just_closed
  alias: Mark garage door just closed
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_door_distance_sensor
    above: 100
  action:
    - service: input_select.select_option
      entity_id: input_select.select_option
      data:
        entity_id: input_select.garage_door_status_dropdown
        option: 'Just Closed'

- id: mark_garage_door_closed
  alias: Mark garage door closed
  trigger:
    platform: state
    entity_id: input_select.garage_door_status_dropdown
    to: 'Just Closed'
    for:
      minutes: 2
  action:
    - service: input_select.select_option
      entity_id: input_select.select_option
      data:
        entity_id: input_select.garage_door_status_dropdown
        option: Closed

- id: mark_garage_door_just_closed_with_parked_car
  alias: Mark garage door just closed with parked car
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_door_distance_sensor
    below: 80
  action:
    - service: input_select.select_option
      entity_id: input_select.select_option
      data:
        entity_id: input_select.garage_door_status_dropdown
        option: 'Just Closed (Car Parked)'

- id: mark_garage_door_closed_with_parked_car
  alias: Mark garage door closed with parked car
  trigger:
    platform: state
    entity_id: input_select.garage_door_status_dropdown
    to: 'Just Closed (Car Parked)'
    for:
      minutes: 2
  action:
    - service: input_select.select_option
      entity_id: input_select.select_option
      data:
        entity_id: input_select.garage_door_status_dropdown
        option: 'Closed (Car Parked)'

# Suite
- id: turn_on_suite_heat_at_late_afternoon
  alias: Turn on suite heat at late afternoon
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_fan_mode
      data:
        entity_id: climate.suite_ac
        fan_mode: auto
    - service: climate.set_operation_mode
      data:
        entity_id: climate.suite_ac
        operation_mode: heat
    - service: climate.set_temperature
      data:
        entity_id: climate.suite_ac
        temperature: 22
    - service: notify.family
      data:
        message: The AC has been turned on in the suite.

- id: turn_off_suite_heat_at_late_night
  alias: Turn off suite heat at late night
  trigger:
    platform: time
    at: '00:30:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.suite_ac
        operation_mode: idle
    - service: notify.family
      data:
        message: The AC has been turned off in the suite.
