- id: notify_if_front_door_was_opened
  alias: Notify if front door was opened
  trigger:
  - entity_id: binary_sensor.front_door_sensor
    platform: state
    to: 'on'
  action:
  - data:
      message: The front door was opened.
    service: notify.family
- id: update_available
  alias: Update available
  trigger:
    platform: state
    entity_id: updater.updater
  action:
  - data:
      message: An update for Home Assistant is available.
    service: notify.family
- id: turn_on_hall_light_when_door_is_opened_and_nobody_is_home
  alias: Turn on hall light when door is opened and nobody is home
  trigger:
  - entity_id: binary_sensor.front_door_sensor
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: group.family
    state: not_home
  action:
  - data:
      entity_id: switch.hall_socket_switch
    service: switch.turn_on
- id: turn_on_hall_light_when_sun_sets
  alias: Turn on hall light when sun sets
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      entity_id: switch.hall_socket_switch
    service: switch.turn_on
- id: turn_off_hall_light_when_sun_rises
  alias: Turn off hall light when sun rises
  trigger:
  - event: sunrise
    offset: -00:45:00
    platform: sun
  action:
  - data:
      entity_id: switch.hall_socket_switch
    service: switch.turn_off
- id: turn_off_outdoor_lights_when_sun_rises
  alias: Turn off outdoor lights when sun rises
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  action:
  - data:
      entity_id: switch.basement_outdoor_lights_switch
    service: switch.turn_off
  - data:
      message: The outdoor lights have been turned off.
    service: notify.family
- id: turn_on_outdoor_lights_when_sun_sets
  alias: Turn on outdoor lights when sun sets
  trigger:
  - event: sunset
    offset: +00:15:00
    platform: sun
  action:
  - data:
      entity_id: switch.basement_outdoor_lights_switch
    service: switch.turn_on
  - data:
      message: The outdoor lights have been turned on.
    service: notify.family
- id: turn_off_garden_sprinklers_station_1_after_timer
  alias: Turn off garden sprinklers station 1 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_1_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_1_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_1_switch
- id: turn_off_garden_sprinklers_station_2_after_timer
  alias: Turn off garden sprinklers station 2 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_2_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_2_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_2_switch
- id: turn_off_garden_sprinklers_station_3_after_timer
  alias: Turn off garden sprinklers station 3 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_3_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_3_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_3_switch
- id: turn_off_garden_sprinklers_station_4_after_timer
  alias: Turn off garden sprinklers station 4 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_4_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_4_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_4_switch
- id: turn_off_garden_sprinklers_station_5_after_timer
  alias: Turn off garden sprinklers station 5 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_5_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_5_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_5_switch
- id: turn_off_garden_sprinklers_station_7_after_timer
  alias: Turn off garden sprinklers station 7 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_7_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_7_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_7_switch
