- id: notify_if_front_door_was_opened
  alias: Notify if front door was opened
  trigger:
  - entity_id: binary_sensor.front_door_sensor
    platform: state
    to: 'on'
  action:
  - data:
      message: The front door was opened.
    service: notify.family
- id: update_available
  alias: Update available
  trigger:
    platform: state
    entity_id: updater.updater
  action:
  - data:
      message: An update for Home Assistant is available.
    service: notify.family

- id: turn_on_hall_light_when_door_is_opened_sun_is_set_and_nobody_is_home
  alias: Turn on hall light when door is opened, sun is set and nobody is home
  trigger:
    platform: state
    entity_id: binary_sensor.hall_front_door_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: switch.turn_on
    entity_id: switch.hall_presence_light_switch

- id: turn_on_hall_presence_light_when_sun_sets
  alias: Turn on hall presence light when sun sets
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.hall_presence_light_switch

- id: turn_off_hall_presence_light_when_sun_rises
  alias: Turn off hall presence light when sun rises
  trigger:
    platform: sun
    event: sunrise
    offset: -00:45:00
  action:
    service: switch.turn_off
    entity_id: switch.hall_presence_light_switch

# Garden
- id: turn_off_garden_lights_when_sun_rises
  alias: Turn off garden lights when sun rises
  trigger:
    platform: sun
    event: sunrise
    offset: -00:30:00
  action:
    - service: switch.turn_off
      entity_id: switch.basement_outdoor_lights_switch
    - delay: 00:00:10
    - service: notify.family
      data:
        data:
          photo:
            caption: The garden lights have been turned off.
            url: '{{ states.sensor.homeassistant_base_url.state ~ states.camera.rear.attributes.entity_picture }}'
        message: Message is ignored

- id: turn_on_garden_lights_when_sun_sets
  alias: Turn on garden lights when sun sets
  trigger:
    platform: sun
    event: sunset
    offset: +00:15:00
  action:
    - service: switch.turn_on
      entity_id: switch.basement_outdoor_lights_switch
    - delay: 00:00:10
    - service: notify.family
      data:
        data:
          photo:
            caption: The garden lights have been turned on.
            url: '{{ states.sensor.homeassistant_base_url.state ~ states.camera.rear.attributes.entity_picture }}'
        message: Message is ignored

- id: turn_off_garden_sprinklers_station_1_after_timer
  alias: Turn off garden sprinklers station 1 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_1_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_1_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_1_switch
- id: turn_off_garden_sprinklers_station_2_after_timer
  alias: Turn off garden sprinklers station 2 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_2_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_2_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_2_switch
- id: turn_off_garden_sprinklers_station_3_after_timer
  alias: Turn off garden sprinklers station 3 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_3_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_3_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_3_switch
- id: turn_off_garden_sprinklers_station_4_after_timer
  alias: Turn off garden sprinklers station 4 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_4_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_4_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_4_switch
- id: turn_off_garden_sprinklers_station_5_after_timer
  alias: Turn off garden sprinklers station 5 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_5_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_5_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_5_switch
- id: turn_off_garden_sprinklers_station_7_after_timer
  alias: Turn off garden sprinklers station 7 after timer
  trigger:
  - entity_id: switch.garden_sprinklers_station_7_switch
    platform: state
    to: 'on'
  action:
  - delay: 00:{{ states.input_number.garden_sprinklers_station_7_slider.state | int }}:00
  - service: switch.turn_off
    data:
      entity_id: switch.garden_sprinklers_station_7_switch
