# Global configuration.
homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  customize: !include includes/customize.yaml

# Enable editable automations (requires file on root).
automation: !include automations.yaml

# Enable the configuration component.
config:

# Enable discovery of supported devices automatically.
discovery:

# Enable the frontend component.
frontend:

# Enable support for tracking state changes over time.
history:

# Enable the iOS component.
ios:

# View all events in a logbook.
logbook:

# Track the sun.
sun:

# Include additional configuration files.
camera: !include includes/camera.yaml
device_tracker: !include includes/device_tracker.yaml
group: !include_dir_merge_named groups/
http: !include includes/http.yaml
input_number: !include includes/input_number.yaml
logger: !include includes/logger.yaml
media_player: !include includes/media_player.yaml
mqtt: !include includes/mqtt.yaml
notify: !include includes/notify.yaml
sensor: !include includes/sensor.yaml
switch: !include includes/switch.yaml
telegram_bot: !include includes/telegram_bot.yaml
updater: !include includes/updater.yaml
zwave: !include includes/zwave.yaml
