- platform: template
  sensors:
    main_door_sensor:
      value_template: "{{ is_state('sensor.main_door', 'off-release') }}"
      friendly_name: Front Door
      device_class: door
      entity_id: sensor.main_door

- platform: template
  sensors:
    laundry_washing_machine:
      delay_on:
        minutes: 5
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.laundry_washer_power_consumption_sensor')|float > 20 }}
