- platform: mqtt
  name: Laundry Washer Power Sensor
  device_class: power
  state_topic: /home/laundry/washer/power
  payload_on: '1'
  payload_off: '0'
  value_template: '{{ (value|int > 10)|int }}'
