- platform: mqtt
  device_class: garage
  name: Garage door
  command_topic: /ha-garage-door-sensor/cmd
  payload_open: 'pulse,5,1,500'
  payload_close: 'pulse,5,1,500'
  payload_stop: 'pulse,5,1,500'
  state_topic: /home/garage/garage-door/distance
  state_open: true
  state_closed: false
  value_template: '{{ 0 < value|int < 20 }}'
