- platform: yr

- platform: airvisual
  api_key: !secret sensor_airvisual
  monitored_conditions:
    - us
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude

- platform: mqtt
  name: Laundry Washer Power Consumption Sensor
  state_topic: /home/laundry/washer/power
  unit_of_measurement: W

- platform: mqtt
  name: Laundry Washer Current Consumption Sensor
  state_topic: /home/laundry/washer/current
  unit_of_measurement: A

- platform: template
  sensors:
    homeassistant_base_url:
      value_template: !secret homeassistant_base_url

- platform: rest
  name: Garden Sprinklers Last Run Sensor
  resource: !secret sensor_garden_sprinklers_last_run_sensor_resource
  value_template: '{{ value_json.lrun[3] | timestamp_local }}'

- platform: wunderground
  api_key: !secret sensor_wunderground_api_key
  pws_id: !secret sensor_wunderground_pws_id
  monitored_conditions:
    - alerts
    - precip_1d
    - precip_1d_mm
    - temp_c
    - temp_high_1d_c
    - temp_low_1d_c
    - UV
    - weather_1d_metric
    - weather_1n_metric
    - weather_2d_metric
    - weather_2n_metric
    - weather_3d_metric
    - weather_3n_metric
    - weather_4d_metric
    - weather_4n_metric
    - wind_1d_kph
    - wind_kph
