- platform: yr

- platform: airvisual
  api_key: !secret sensor_airvisual
  monitored_conditions:
    - us
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude

- platform: mqtt
  name: Basement Temperature Sensor
  state_topic: /home/basement/temperature-humidity-sensor/temperature
  unit_of_measurement: 째C

- platform: mqtt
  name: Basement Humidity Sensor
  state_topic: /home/basement/temperature-humidity-sensor/humidity
  unit_of_measurement: '%'

- platform: mqtt
  name: Laundry Washer Power Consumption Sensor
  state_topic: /home/laundry/washer/power
  unit_of_measurement: W

- platform: history_stats
  name: Laundry Washer Time On Today
  entity_id: binary_sensor.laundry_washing_machine
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Laundry Washer Times On Today
  entity_id: binary_sensor.laundry_washing_machine
  state: 'on'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: zigate
  name: Living Room Temperature Sensor
  address: !secret sensor_living_room_temperature_sensor_address
  default_state: temperature
  default_unit: '째C'

- platform: template
  sensors:
    living_room_pressure_sensor:
      friendly_name: Living Room Atmospheric Pressure
      unit_of_measurement: 'mb'
      value_template: '{{ states.sensor.living_room_temperature_sensor.attributes.pressure }}'
    living_room_humidity_sensor:
      friendly_name: Living Room Humidity
      unit_of_measurement: '%'
      value_template: '{{ states.sensor.living_room_temperature_sensor.attributes.humidity }}'

- platform: mqtt
  name: Garage Door Distance Sensor
  state_topic: /home/garage/garage-door/distance
  unit_of_measurement: cm

- platform: template
  sensors:
    garage_door_status_sensor:
      friendly_name: Door
      value_template: '{{ states.input_select.garage_door_status_dropdown.state }}'
      entity_id: input_select.garage_door_status_dropdown

- platform: template
  sensors:
    homeassistant_base_url:
      value_template: !secret homeassistant_base_url

- platform: rest
  name: Garden Sprinklers Last Run Sensor
  resource: !secret sensor_garden_sprinklers_last_run_sensor_resource
  value_template: '{{ value_json.lrun[3] | timestamp_local }}'

- platform: mqtt
  name: Suite Temperature Sensor
  state_topic: /home/suite/temperature-humidity-sensor/temperature
  unit_of_measurement: 째C

- platform: mqtt
  name: Suite Humidity Sensor
  state_topic: /home/suite/temperature-humidity-sensor/humidity
  unit_of_measurement: '%'

- platform: zigate
  name: Suite Bathroom Temperature Sensor
  address: !secret sensor_suite_bathroom_temperature_sensor_address
  default_state: temperature
  default_unit: '째C'

- platform: template
  sensors:
    suite_bathroom_pressure_sensor:
      friendly_name: Suite Bathroom Atmospheric Pressure
      unit_of_measurement: 'mb'
      value_template: '{{ states.sensor.suite_bathroom_temperature_sensor.attributes.pressure }}'
    suite_bathroom_humidity_sensor:
      friendly_name: Suite Bathroom Humidity
      unit_of_measurement: '%'
      value_template: '{{ states.sensor.suite_bathroom_temperature_sensor.attributes.humidity }}'

- platform: wunderground
  api_key: !secret sensor_wunderground_api_key
  pws_id: !secret sensor_wunderground_pws_id
  monitored_conditions:
    - alerts
    - precip_1d
    - precip_1d_mm
    - temp_c
    - temp_high_1d_c
    - temp_low_1d_c
    - UV
    - weather_1d_metric
    - weather_1n_metric
    - weather_2d_metric
    - weather_2n_metric
    - weather_3d_metric
    - weather_3n_metric
    - weather_4d_metric
    - weather_4n_metric
    - wind_1d_kph
    - wind_kph

- platform: zigate
  address: !secret sensor_main_door_address
  name: Main Door
  default_state: 'state'
