- platform: mqtt
  name: Living Room Sofa Corner Light Switch
  availability_topic: /home/living-room/sofa-corner-light/status
  command_topic: /home/living-room/sofa-corner-light/relay/0/set
  state_topic: /home/living-room/sofa-corner-light/relay/0
  payload_available: '1'
  payload_not_available: '0'
  payload_off: '0'
  payload_on: '1'

- platform: mqtt
  name: Basement Outdoor Lights Switch
  availability_topic: /home/basement/outdoor-lights/status
  command_topic: /home/basement/outdoor-lights/relay/0/set
  state_topic: /home/basement/outdoor-lights/relay/0
  payload_available: '1'
  payload_not_available: '0'
  payload_off: '0'
  payload_on: '1'

- platform: command_line
  scan_interval: 60
  switches:
    garden_sprinklers_station_1_switch:
      command_on: !secret switch_switches_garden_sprinklers_station_1_switch_command_on
      command_off: !secret switch_switches_garden_sprinklers_station_1_switch_command_off
      command_state: !secret switch_switches_garden_sprinklers_station_1_switch_command_state
      value_template: '{% if value_json %}{{ value_json.sn[0] == 1 }}{% else %}{{ False }}{% endif %}'

    garden_sprinklers_station_2_switch:
      command_on: !secret switch_switches_garden_sprinklers_station_2_switch_command_on
      command_off: !secret switch_switches_garden_sprinklers_station_2_switch_command_off
      command_state: !secret switch_switches_garden_sprinklers_station_2_switch_command_state
      value_template: '{% if value_json %}{{ value_json.sn[1] == 1 }}{% else %}{{ False }}{% endif %}'

    garden_sprinklers_station_3_switch:
      command_on: !secret switch_switches_garden_sprinklers_station_3_switch_command_on
      command_off: !secret switch_switches_garden_sprinklers_station_3_switch_command_off
      command_state: !secret switch_switches_garden_sprinklers_station_3_switch_command_state
      value_template: '{% if value_json %}{{ value_json.sn[2] == 1 }}{% else %}{{ False }}{% endif %}'

    garden_sprinklers_station_4_switch:
      command_on: !secret switch_switches_garden_sprinklers_station_4_switch_command_on
      command_off: !secret switch_switches_garden_sprinklers_station_4_switch_command_off
      command_state: !secret switch_switches_garden_sprinklers_station_4_switch_command_state
      value_template: '{% if value_json %}{{ value_json.sn[3] == 1 }}{% else %}{{ False }}{% endif %}'

    garden_sprinklers_station_5_switch:
      command_on: !secret switch_switches_garden_sprinklers_station_5_switch_command_on
      command_off: !secret switch_switches_garden_sprinklers_station_5_switch_command_off
      command_state: !secret switch_switches_garden_sprinklers_station_5_switch_command_state
      value_template: '{% if value_json %}{{ value_json.sn[4] == 1 }}{% else %}{{ False }}{% endif %}'

    garden_sprinklers_station_6_switch:
      command_on: !secret switch_switches_garden_sprinklers_station_6_switch_command_on
      command_off: !secret switch_switches_garden_sprinklers_station_6_switch_command_off
      command_state: !secret switch_switches_garden_sprinklers_station_6_switch_command_state
      value_template: '{% if value_json %}{{ value_json.sn[5] == 1 }}{% else %}{{ False }}{% endif %}'

    garden_sprinklers_station_7_switch:
      command_on: !secret switch_switches_garden_sprinklers_station_7_switch_command_on
      command_off: !secret switch_switches_garden_sprinklers_station_7_switch_command_off
      command_state: !secret switch_switches_garden_sprinklers_station_7_switch_command_state
      value_template: '{% if value_json %}{{ value_json.sn[6] == 1 }}{% else %}{{ False }}{% endif %}'

- platform: broadlink
  host: !secret climate_living_room_ac_host
  mac: !secret climate_living_room_ac_mac

- platform: broadlink
  host: !secret climate_suite_ac_host
  mac: !secret climate_suite_ac_mac
